### ISSUE TITLE
npm install fail

### ISSUE THREAD

**Issue by CJ42** [honestbonsai/drizzle-react-native-box#5]
I cannot install the packages by running `npm install`

I get the following errors: 

```
8 warnings and 7 errors generated.
make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jeancavallera/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Users/jeancavallera/.nvm/versions/node/v12.14.1/bin/node" "/Users/jeancavallera/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jeancavallera/Desktop/Documents/Business/Extropy.io/cevt_drizzle/node_modules/scrypt
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jeancavallera/.npm/_logs/2020-04-22T19_36_52_817Z-debug.log
```

**Comment by shl0k28** [comment]
This is a bug if you are using a version on node 12.x.
Try downgrading it to node version 10.16.3(previous LTS version).
This should solve the error.
