### ISSUE TITLE
Setting up box failed.

### ISSUE THREAD

**Issue by spaceh3ad** [honestbonsai/drizzle-react-native-box#7]
Hi, i am unable to unbox truffle box. I get the following error:
Any ideas?

`truffle unbox drizzle-react-native`

```
Starting unbox...
=================

✔ Preparing to download box
✔ Downloading
warning ../../package.json: No license field
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/frozeman/WebSocket-Node.git
Directory: /home/josh/GitHub/react-tubbly
Output:
fatal: unable to connect to github.com:
github.com[0: 140.82.121.4]: errno=Connection timed out
✔ Cleaning up temporary files
✖ Setting up box
Unbox failed!
✖ Setting up box
Unbox failed!
Error: Command failed: yarn
warning ../../package.json: No license field
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/frozeman/WebSocket-Node.git
Directory: ~ /my-dir/app
Output:
fatal: unable to connect to github.com:
github.com[0: 140.82.121.4]: errno=Connection timed out

    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.installBoxDependencies (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:138:1)
    at Object.setUpBox (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/index.js:66:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:116:1
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:5:42)
Truffle v5.3.3 (core: 5.3.3)
Node v14.14.0

```

**Comment by grenos** [comment]
+1

**Comment by Olshansk** [comment]
Seems like this library is no longer supported?
